---
blank_issues_enabled: false

contact_links:
  - name: ğŸ“– Documentation
    url: https://hamyarpaygahpy.readthedocs.io/en/latest/
    about: Check the documentation before opening an issue.

  - name: ğŸ’¬ Discussions
    url: https://github.com/MohsenHNSJ/HamyarPaygahPy/discussions
    about: Ask questions, share ideas, or start conversations.

  - name: ğŸ” Report a security vulnerability
    url: https://github.com/MohsenHNSJ/HamyarPaygahPy/security/advisories/new
    about: Please report security vulnerabilities privately.
