---
name: CodSpeed Benchmarks

on:
  push: # Run on every Push
  pull_request: # Run on every PR
  # `workflow_dispatch` allows CodSpeed to trigger back-test
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write
  id-token: write # For OpenID Connect authentication with CodSpeed

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit # Monitor outbound connections

      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Ensure Poetry cache directory exists
        run: mkdir -p ~/.cache/pypoetry

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Print pip cache status
        run: |
          echo "pip cache hit: ${{ steps.cache-pip.outputs.cache-hit }}"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Print Poetry cache status
        run: |
          echo "poetry cache hit: ${{ steps.cache-poetry.outputs.cache-hit }}"

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          install-package: true
          pytest: true
          aiohttp: true
          pytest-asyncio: true
          pytest-codspeed: true
          pydantic: true

      - name: Run benchmark
        uses: CodSpeedHQ/action@e736f0d2aeb36da38e9f08eca4dff7967408d154 # v4.8.2
        with:
          mode: simulation # Run the benchmarks with CPU simulation measurements.
          run: pytest tests/ --codspeed -rA
