---
name: Compatibility and Coverage Tests

on:
  push: # Run on every Push
  pull_request: # Run on every PR

permissions: read-all

jobs:
  compatibility-tests:
    name: Compatibility with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    env:
      NOXSESSION: test-and-coverage
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit # Monitor outbound connections

      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Ensure Poetry cache directory exists
        run: mkdir -p ~/.cache/pypoetry

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Print pip cache status
        run: |
          echo "pip cache hit: ${{ steps.cache-pip.outputs.cache-hit }}"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-poetry-

      - name: Print Poetry cache status
        run: |
          echo "poetry cache hit: ${{ steps.cache-poetry.outputs.cache-hit }}"

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
          nox: true

      - name: Run Nox
        run: |
          nox -s test-${{ matrix.python-version }}

      # IDEs may warn about env.PYTHON_VERSION might be invalid, but it is a valid environment variable and set at runtime.
      - name: Upload coverage data
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: coverage-data${{ env.PYTHON_VERSION }}
          path: ".coverage.*"
          include-hidden-files: true
          compression-level: 9

  coverage:
    name: Produce coverage report
    runs-on: ubuntu-latest
    needs: compatibility-tests
    permissions:
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit # Monitor outbound connections

      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          coverage: true
          nox: true

      - name: Download coverage data
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          pattern: coverage-data*

      - name: Move coverage files to root folder
        run: |
          find ~/ -type f -name '.coverage.*' -exec mv -t /home/runner/work/HamyarPaygahPy/HamyarPaygahPy/ {} +

      - name: Combine coverage data and report
        run: |
          nox -s coverage-3.13

      - name: Upload coverage report To Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          # Disable search for coverage files.
          # This is helpful when specifying what files you want to upload with the files option.
          disable_search: true
          # On error, exit with non-zero code
          fail_ci_if_error: true
          # Comma-separated explicit list of files to upload.
          # These will be added to the coverage files found for upload.
          # If you wish to only upload the specified files, please consider using "disable-search" to disable uploading other files.
          files: ./coverage.xml
          # Use OIDC instead of token. This will ignore any token supplied
          use_oidc: true
          # Enable verbose logging
          verbose: true
