---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: Run MegaLinter

on:
  push: # Run on every Push
  pull_request: # Run on every PR

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  mega-linter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
      # Remove the ones you do not need
      contents: read
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit # Monitor outbound connections

      # Git Checkout
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/latest/flavors/
        uses: oxsecurity/megalinter/flavors/ci_light@42bb470545e359597e7f12156947c436e4e3fb9a # v9.3.0
        env:
          # https://megalinter.io/latest/configuration/
          # Disable linters in the listed descriptors
          DISABLE: COPYPASTE
          # Disable specific linters
          DISABLE_LINTERS: JSON_PRETTIER,YAML_PRETTIER
          # Report results to GitHub status checks
          GITHUB_STATUS_REPORTER: true
          # Python default style to check/apply.
          PYTHON_DEFAULT_STYLE: ruff
          # Displays elapsed time in reports
          SHOW_ELAPSED_TIME: true
          # Validate all files in the codebase, not only modified files
          VALIDATE_ALL_CODEBASE: true
