---
name: Safety-CLI Scanner

# Safety CLI in free tier has a limit of 100 checks per month
# So we only run in for Pushes and PRs to main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  safety-cli:
    name: Run Safety-CLI
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit # Monitor outbound connections

      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@2591cf2f3e67ba68b923f4c92f0d36e281c65023 # v1.0.1
        with:
          api-key: ${{ secrets.SAFETY_CLI_API }}
          args: --detailed-report # To always see detailed output from this action
